### ISSUE TITLE
data/warns/warns.dat doesn't exist

### ISSUE THREAD

**Issue by simoniz0r** [XNBlank/sudoBot#5]
```Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/simonizor/.local/lib/python3.5/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 75, in on_ready
    await decayWarn();
  File "bot.py", line 18, in decayWarn
    with open(dataFile, 'r', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/warns/warns.dat'
False
Ignoring exception in command warn
Traceback (most recent call last):
  File "/home/simonizor/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/simonizor/sudoBot/cogs/mod.py", line 195, in warn
    async with open(dataFile, 'w', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/warns/warns.dat'
```

**Comment by simoniz0r** [comment]
I've tried creating the file myself, but that completely kills the bot.  I'm guessing that it's expecting some formatting within the file that I'm not aware of.

**Comment by XNBlank** [comment]
The formatting is json. Setting this in the empty file should make it work fine.
`{ }`
I'll push a quick update soon.

**Comment by XNBlank** [comment]
https://github.com/XNBlank/sudoBot/commit/ae07693fbbf4f5af56ebe006d1c01315b8f791ea
